<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <parent>
        <artifactId>lutece-global-pom</artifactId>
        <groupId>fr.paris.lutece.tools</groupId>
        <version>7.0.5</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.paris.lutece.plugins</groupId>
    <artifactId>plugin-deviceregistration</artifactId>
    <packaging>lutece-plugin</packaging>
    <version>1.0.1</version>
    <name>Lutece deviceregistration plugin</name>

    <repositories>
        <repository>
            <id>lutece</id>
            <name>luteceRepository</name>
            <url>https://dev.lutece.paris.fr/maven_repository</url>
            <layout>default</layout>
        </repository>
        <repository>
            <id>luteceSnapshot</id>
            <name>luteceSnapshot</name>
            <url>https://dev.lutece.paris.fr/snapshot_repository</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <releases>
                <enabled>false</enabled>
            </releases>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>fr.paris.lutece</groupId>
            <artifactId>lutece-core</artifactId>
            <version>[7.0.0,7.9.9)</version>
            <type>lutece-core</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-rest</artifactId>
            <version>[3.0.0,3.9.9)</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-jaxrs</artifactId>
            <version>${swagger.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>javax.ws.rs</groupId>
                    <artifactId>jsr311-api</artifactId>
                </exclusion>
            </exclusions>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>${swagger.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-swaggerui</artifactId>
            <version>[1.0.1,1.9.9)</version>
            <type>lutece-plugin</type>
        </dependency>
    </dependencies>

    <properties>
        <componentName>deviceregistration</componentName>
        <jiraProjectName>DEVICEREGISTRATION</jiraProjectName>
        <jiraComponentId />
        <java.version>11</java.version>
        <swagger.version>1.6.16</swagger.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.github.kongchen</groupId>
                <artifactId>swagger-maven-plugin</artifactId>
                <version>3.1.6</version>
                <configuration>
                    <apiSources>
                        <apiSource>
                            <springmvc>false</springmvc>
                            <locations>fr.paris.lutece.plugins.deviceregistration.rs.DeviceRegistrationRest</locations>
                            <basePath>$${context}</basePath>
                            <info>
                                <title>DeviceRegistration API</title>
                                <version>V1</version>
                                <description>This API can be used to manage deviceRegistration</description>
                            </info>
                            <swaggerDirectory>${basedir}/webapp/plugins/deviceregistration/api/swagger/v1</swaggerDirectory>
                        </apiSource>
                    </apiSources>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <scm>
        <connection>scm:git:https://github.com/lutece-secteur-public/gru-plugin-deviceregistration.git</connection>
        <developerConnection>scm:git:https://github.com/lutece-secteur-public/gru-plugin-deviceregistration.git</developerConnection>
        <url>https://github.com/lutece-secteur-public/gru-plugin-deviceregistration.git</url>
        <tag>plugin-deviceregistration-1.0.1</tag>
    </scm>
        

</project>
